# Generated by Django 5.0.7 on 2025-09-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
